spring:
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  redis:
    host: 192.168.1.140
  # Redis服务器连接端口
    port: 6379
    database: 0
  # Redis服务器连接密码（默认为空）
    password: kaiJ@168
  # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 30
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  # 连接池中的最大空闲连接
        max-idle: 8
  # 连接池中的最小空闲连接
        min-idle: 0
  # 连接超时时间（毫秒）
    timeout: 30000

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true  #  消息发送到交换机确认机制,是否返回回馈
    virtual-host: / #默认主机

#自定义参数
defineProps:
  rabbitmq:
    topic: vn.topic
    queue: vn.queue
    # *表号匹配一个word，#匹配多个word和路径，路径之间通过.隔开
    queue1_pattern: vn.north.#
    # *表号匹配一个word，#匹配多个word和路径，路径之间通过.隔开
    queue2_pattern: vn.south.#
    queuename:
      north: north-queue
      south: south-queue